contact_links:
  - name: "ğŸ” Look for my Issue"
    url: https://github.com/kernelkit/infix/issues?q=is%3Aissue+sort%3Acreated-desc+
    about: Thank â¤ï¸ you for your time! We kindly ask that you first check if an issue already exists.
  - name: "ğŸ’¬ Discussions and Q&A"
    url: https://github.com/kernelkit/infix/discussions
    about: Discussions are perfect for quick questions, bouncing ideas, and things that may be a bug.
