[tool.poetry]
name = "infix-show"
version = "1.0"
description = "Infix show commands"
license = "MIT"
packages = [
    { include = "show" }
]
authors = [
  "KernelKit developers"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
show = "show:main"
